# playbook.yml
- name: deploy frontend to host
  hosts: frontend

  tasks:
  - name: checkout frontend code on host
    git:
      repo: git@github.com:And0r-/MatrixRegisterFrontend.git
      dest: ~/projects/MatrixRegisterFrontend

  - name: build docker image
    become: true
    docker_image:
      name: matrix_register_frontend
      build:
        path: /home/andreas/projects/MatrixRegisterFrontend
      source: build
      state: present
      force_source: yes
      debug: yes

  - name: restart docker image
    become: true
    docker_container:
      name: matrix_register_frontend
      image: matrix_register_frontend
      recreate: yes
      ports:
        - "49172:3000"
